TodoList/Models/Statistiques.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TodoList.Models
{
    public class Statistiques
    {
        public int NbTachesTerminees { get; set; }
        public int NbTachesEnCours { get; set; }
        public int NbTachesRetard { get; set; }
        public int MoyenneTpsTaches { get; set; }
    }
}

TodoList/Controllers/TachesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TodoList.Models;

namespace TodoList.Controllers
{
    // Ajouter un contrôleur de type « Contrôleur MVC avec vues utilisant EF », qui utilise la classe Tache comme modèle et le contexte de données qu’on vient de créer. Laisser la case « Générer des vues » cochée.

    public class TachesController : Controller
    {
        private readonly TodoListContext _context;

        public TachesController(TodoListContext context)
        {
            _context = context;
        }

        // GET: Taches
        public async Task<IActionResult> Index(int etat, string recherche)
        {   // On souhaite appeler la modale depuis la liste des tâches. Or la liste utilise une liste de tâches comme modèle, tandis que la modale utilisera une tâche unique
            // On va donc faire en sorte d’ajouter systématiquement un élément vide à la fin de la liste des tâches pour le réserver comme modèle de la fenêtre modale
            // Dans l’action Index du contrôleur, avant de renvoyer la liste des tâches, ajouter une tâche vide à la fin de la liste (initialiser simplement sa date de création à la date du jour)
            // Pour se faire on cré une nouvelle variable appelé tache que l'on initialise à la date du jour et que l'on injecte dans return View
            // Dans la vue Index, faire en sorte que cette tâche ne soit jamais affichée, ni comptabilisée dans les compteurs
            // var tache = await _context.Tache.ToListAsync();
            // tache.Add(new Tache() { DateCreation = DateTime.Now });
            // return View(await _context.Tache.ToListAsync());

            IQueryable<Tache> request= _context.Tache; 
            

            // Dans la vue de la liste des tâches, entre le titre et le tableau, ajouter les éléments de filtres suivants: La zone de texte permet de filtrer les tâches dont la description contient le texte saisi et liste déroulante permet de filtrer les tâches selon leur état (terminées, non terminées, toutes)
            // Valeurs pour la liste déroulante Tâches
            var dicTaches = new Dictionary<int, string>()
            {
               { 1, "En cours" },
               { 2, "Terminée" },
               { 3, "Toutes" }
            };

            if(etat == 0)
            {
                // Lecture d’une valeur dans un cookie
                if (Request.Cookies.TryGetValue("etatfiltre", out string val))
                {
                    int.TryParse(val, out etat);
                }
            }

            // Ecriture d’une valeur dans un cookie
            var options = new Microsoft.AspNetCore.Http.CookieOptions
            {
                Expires = DateTime.Now.AddMinutes(5) // Le cookie expirera dans 5 minutes 
            };
            Response.Cookies.Append("etatfiltre", etat.ToString(), options);

            // Mémorise / transmet les valeurs de la liste, ainsi que la valeur sélectionnée
            ViewBag.Etat = new SelectList(dicTaches, "Key", "Value", etat);

            // Filtrer
            if(recherche != null)
            {
                if (etat == 1)
                {
                    request = request.Where(t => t.Terminee == false && t.Description.Contains(recherche));
                }


                if (etat == 2)
                {
                    request = request.Where(t => t.Terminee == true && t.Description.Contains(recherche));
                }
            }

            else if(recherche == null)
            {
                if (etat == 1)
                {
                    request = request.Where(t => t.Terminee == false);
                }


                if (etat == 2)
                {
                    request = request.Where(t => t.Terminee == true);
                }
            }

                List<Tache> list= await request.ToListAsync();
                list.Add(new Tache() { DateCreation = DateTime.Now }); // On remet l'ajout de la tâche vide utilisée dans le formaulaire du modal
                return View(list);
        }

        // GET: Taches/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tache = await _context.Tache
                .FirstOrDefaultAsync(m => m.id == id);
            if (tache == null)
            {
                return NotFound();
            }

            return View(tache);
        }

        // GET: Taches/Create
        public IActionResult Create()
        {
            return View();
        }

        // Ajouter une entrée « Statistiques » dans le menu principal de l’application, qui appellera une action de même nom dans le contrôleur des tâches
        public async Task<IActionResult> Statistiques()
        {
            var taches = await _context.Tache.ToListAsync();

            var stats = new Statistiques();
            stats.NbTachesTerminees = taches.Where(p => p.Terminee == true).Count();
            stats.NbTachesEnCours = taches.Where(p => p.Terminee == false).Count();
            stats.NbTachesRetard = taches.Where(p => p.DateEcheance < DateTime.Now).Count();

            foreach(var item in taches)
            {
                TimeSpan datediff = (TimeSpan)(item.DateEcheance - item.DateCreation);
                stats.MoyenneTpsTaches = stats.MoyenneTpsTaches + datediff.Days;
            }

            stats.MoyenneTpsTaches = stats.MoyenneTpsTaches / taches.Count();
            // Créer une nouvelle vue « Statistiques » pour le contrôleur des tâches et faire en sorte qu’elle affiche les informations ci-dessus dans de simples libellés
            return View("Statistiques", stats);
        }

        // POST: Taches/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,Description,DateCreation,DateEcheance,Terminee")] Tache tache)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tache);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tache);
        }
        public IActionResult InitSaisie()
        {
            return View("CreationGroupee");
        }

        // Dans la vue CreationGroupee, créer le formulaire permettant de saisir le nombre de tâches à créer. Ce formulaire doit appeler une action InitSaisie de type Post 
        // Pour passer le nombre de tâches saisie à l’action, il suffit d’affecter à la zone de saisie un nom (propriété name) identique à celui du paramètre de l’action
        [HttpPost]
        public IActionResult InitSaisie(int nbTaches)
        {
            // Instancier une liste de x tâches (x étant la valeur reçue en paramètre) dont la date d’échéance est à la date du jour + 1 semaine
            // Retourner la vue CreationGroupee en lui passant cette liste de tâches. Ceci nous permettra d’initialiser le tableau de tâches vides
            List<Tache> list = new List<Tache>();
            for (int i = 0; i < nbTaches; i++)
            {
                list.Add(new Tache() { DateEcheance = DateTime.Now.AddDays(7) });
            }
            return View("CreationGroupee", list);
        }

        [HttpPost]
        public async Task<IActionResult> CreationGroupee([Bind("Id,Description,DateEcheance")] List<Tache> taches)
        {
            // Dans l’action CreationGroupee, enregistrer les tâches en initialisant leur date de création à la date du jour et en s’inspirant du code de l’action Create
            // Renvoyer la vue Index comme résultat pour rediriger vers la liste des tâches.

            if (ModelState.IsValid)
            {
                foreach (var tache in taches)
                {
                    tache.DateCreation = DateTime.Now;
                    _context.Add(tache);
                }

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View("CreationGroupee", taches);
        }

        // Afficher le formaulaire d'édition en Get
        // GET: Taches/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tache = await _context.Tache.FindAsync(id);
            if (tache == null)
            {
                return NotFound();
            }
            return View(tache);
        }

        // Editer une action et la poster
        // POST: Taches/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,Description,DateCreation,DateEcheance,Terminee")] Tache tache)
        {
            if (id != tache.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tache);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {

TodoList/Controllers/UtilitairesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TodoList.Models;

namespace TodoList.Controllers
{
    public class UtilitairesController : Controller
    {
        public IActionResult Index()
        {
            // Dans l’action Index, instancier une entité Calcul permettant d’initialiser la date de la première zone de saisie à la date du jour. Générer la réponse de la même façon que dans AjouterJours

            var calcul = new Calcul();
            calcul.BaseDate = DateTime.Now;
            calcul.FinalDate = calcul.BaseDate.AddDays(calcul.AddDays);
            return View(calcul);
        }

        // Ajouter une action nommée AjouterJours qui prend en paramètres un objet Calcul. Faire en sorte qu’on puisse l’appeler aussi par l’url « localhost:xxxx/calculsdates »
        /*
        [ActionName("calculdates")]
        public IActionResult AddDays(Calcul calcul)
        {
            ModelState.Remove("FinalDate");
            // ModelState représente l'état de la liaison de modèle (liaison entre la source de données de la vue et les paramètres de l’action) 
            // après saisie des valeurs par l'utilisateur. Il doit être rafraîchi pour que le résultat de l'opération s'affiche. 
            // On peut forcer ce rafraichissement en vidant le ModelState complètement ou seulement la propriété correspondant à la donnée à rafraîchir.
            // Rafraichi les données du Model Binding
            // Sans le modelState le résultat ne s’affiche pas

            calcul.FinalDate = calcul.BaseDate.AddDays(calcul.AddDays);

            return View("Index", calcul);  
        }
        */

        // Faire en sorte que le résultat de l’opération soit désormais transmis à la vue par le ViewBag (ou ViewData) et non plus par l’entité Calcul. On mettra le code créé précédemment en commentaire pour pouvoir y revenir par la suite.
        // Dans la vue, utiliser l’attribut value au lieu de asp-for pour afficher la valeur
        [ActionName("calculdates")]
        public IActionResult AddDays(Calcul calcul)
        {
            if (ModelState.IsValid) 
            { 
                ModelState.Remove("FinalDate");
                // ModelState représente l'état de la liaison de modèle (liaison entre la source de données de la vue et les paramètres de l’action) 
                // après saisie des valeurs par l'utilisateur. Il doit être rafraîchi pour que le résultat de l'opération s'affiche. 
                // On peut forcer ce rafraichissement en vidant le ModelState complètement ou seulement la propriété correspondant à la donnée à rafraîchir.
                // Rafraichi les données du Model Binding
                ViewData["FinalDate"] = calcul.BaseDate.AddDays(calcul.AddDays);
                if(calcul.Operator == "+")
                {
                    ViewData["FinalDate"] = calcul.BaseDate.AddDays(calcul.AddDays);
                }
                if(calcul.Operator == "-")
                {
                    ViewData["FinalDate"] = calcul.BaseDate.AddDays(-calcul.AddDays);
                }
                    return View("Index");
            }

            return View("Index");
        }

        public FileResult Download()
        {
            string fileName = "calendrierdelannee.rar";
            byte[] fileBytes = System.IO.File.ReadAllBytes($"wwwroot/Files/{fileName}");
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }
    }
}

TodoList/Views/Taches/Create.cshtml
@model TodoList.Models.Tache

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>
<!-- Modifier les vues de tâches pour qu’elles s’intègrent bien dans la disposition créée précédemment -->
@section Header {
    <h4>Tache</h4>
}

<div class="row">
    <div class="col-md-4">
        <partial name="_FormCreate">
            <!-- Dans la vue Create, remplacer le formulaire par la vue partielle _FormCreate créé précédemment, en gardant le bouton submit en-dessous -->
            @*
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea> <!-- On remplace l'input par un textarea car l'input ne peut afficher plusieurs lignes -->
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateCreation" class="control-label"></label>
                <input asp-for="DateCreation" class="form-control" />
                <span asp-validation-for="DateCreation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateEcheance" class="control-label"></label>
                <input asp-for="DateEcheance" class="form-control" />
                <span asp-validation-for="DateEcheance" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Terminee" /> @Html.DisplayNameFor(model => model.Terminee)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
            *@

            @*
        @Html.Partial("_FormCreate")
            *@

</div>
</div>
<div>
    <input form="formCreateTask" type="submit" value="Create" class="btn btn-primary" />
    <!-- Ajouter l’attribut form="formCreateTask" sur le bouton submit afin de le relier au formulaire -->
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>
<!-- Modifier les vues de tâches pour qu’elles s’intègrent bien dans la disposition créée précédemment -->
@section Footer {
    <footer>
        <p> &copy; 2020 - TodoList </p>
    </footer>
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TodoList/Views/Taches/CreationGroupee.cshtml
@model List<TodoList.Models.Tache>
<!-- Pour le contrôleur Taches,  ajouter une vue nommée CreationGroupee, de type liste et utilisant l’entité Tache -->

@{
    ViewData["Title"] = "Creation Groupee";
}

<h1>Creation Groupee</h1>
<!-- Modifier les vues de tâches pour qu’elles s’intègrent bien dans la disposition créée précédemment -->
@section Header {

}

<!-- Dans la vue CreationGroupee, créer le formulaire permettant de saisir le nombre de tâches à créer. Ce formulaire doit appeler une action InitSaisie de type Post -->
<!-- Faire en sorte que tant que l’utilisateur n’a pas choisi un nombre de tâches, seul le premier formulaire soit visible. Puis, une fois le nombre de tâches choisi, que seul le second formulaire soit visible -->
@if (Model == null)
{
    <form asp-action="InitSaisie">
        <!-- Pour passer le nombre de tâches saisie à l’action, il suffit d’affecter à la zone de saisie un nom (propriété name) identique à celui du paramètre de l’action -->
        <label>Nombre de tâches à créer : </label>
        <input type="number" name="nbTaches" min="0" /> <!-- Pour passer le nombre de tâches saisie à l’action, il suffit d’affecter à la zone de saisie un nom (propriété name) identique à celui du paramètre de l’action -->
        <input type="submit" class="btn btn-success" value="Créer" />
    </form>
}
<!-- Ajouter le second formulaire qui affiche les tâches à compléter -->
<!-- Le clic sur le bouton Enregistrer doit appeler une action CreationGroupee qui récupérera en paramètre la liste des tâches complétées par l’utilisateur -->
<!-- Placer le tableau dans des conteneur div imbriqués de classes css « row » et « col-md-6 » -->
<!-- Utiliser une boucle for et non foreach pour générer les lignes du tableau, afin que les tâches soient modifiables -->

@if (Model != null)
{
    <form asp-action="CreationGroupee">
        <div class="row">
            <div class="col-md-6">
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model[0].Description)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model[0].DateEcheance)
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (int i = 0; i < Model.Count(); i++)
                        {
                            <tr>
                                <td>
                                    <textarea asp-for="@Model[i].Description" class="form-control"></textarea>
                                </td>
                                <td>
                                    <input asp-for="@Model[i].DateEcheance" class="form-control" />
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <input type="submit" class="btn btn-success" value="Enregistrer" />
    </form>
}

<p>
    <a asp-action="Index">Retour à la liste</a> <!-- En bas de la page, ajouter un lien « Retour à la liste » permettant de revenir à la liste des tâches à tout moment, en abandonnant la saisie éventuellement en cours. -->
</p>
<!-- Modifier les vues de tâches pour qu’elles s’intègrent bien dans la disposition créée précédemment -->
@section Footer {
    <footer>
        <p> &copy; 2020 - TodoList </p>
    </footer>
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TodoList/Views/Taches/Delete.cshtml
@model TodoList.Models.Tache

@{
    ViewData["Title"] = "Delete";
}


<h1>Delete</h1>


<h3>Are you sure you want to delete this?</h3>
<div>
    <!-- Modifier les vues de tâches pour qu’elles s’intègrent bien dans la disposition créée précédemment -->
    @section Header {
        <h4>Tache</h4>
    }

    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateCreation)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateEcheance)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateEcheance)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Terminee)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Terminee)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
<!-- Modifier les vues de tâches pour qu’elles s’intègrent bien dans la disposition créée précédemment -->
@section Footer {
    <footer>
        <p> &copy; 2020 - TodoList </p>
    </footer>
}

TodoList/Views/Taches/Details.cshtml
@model TodoList.Models.Tache

@{
    ViewData["Title"] = "Details";
}


<h1>Details</h1>
<!-- Modifier les vues de tâches pour qu’elles s’intègrent bien dans la disposition créée précédemment -->
<div>
    @section Header {
        <h4>Tache</h4>
    }

    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateCreation)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateEcheance)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateEcheance)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Terminee)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Terminee)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
<!-- Modifier les vues de tâches pour qu’elles s’intègrent bien dans la disposition créée précédemment -->
@section Footer {
    <footer>
        <p> &copy; 2020 - TodoList </p>
    </footer>
}

TodoList/Views/Taches/Edit.cshtml
@model TodoList.Models.Tache

@{
    ViewData["Title"] = "Edit";
}


<h1>Edit</h1>
<!-- Modifier les vues de tâches pour qu’elles s’intègrent bien dans la disposition créée précédemment -->
@section Header {
    <h4>Tache</h4>
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" /></textarea> <!-- On remplace l'input par un textarea car l'input ne peut afficher plusieurs lignes -->
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateCreation" class="control-label"></label>
                <input asp-for="DateCreation" class="form-control" />
                <span asp-validation-for="DateCreation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateEcheance" class="control-label"></label>
                <input asp-for="DateEcheance" class="form-control" />
                <span asp-validation-for="DateEcheance" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Terminee" /> @Html.DisplayNameFor(model => model.Terminee)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
<!-- Modifier les vues de tâches pour qu’elles s’intègrent bien dans la disposition créée précédemment -->
@section Footer {
    <footer>
        <p> &copy; 2020 - TodoList </p>
    </footer>
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TodoList/Views/Taches/Statistiques.cshtml

@model TodoList.Models.Statistiques

@{
    ViewData["Title"] = "Statistiques";
}

<h1>Statistiques</h1>
<!-- Modifier les vues de tâches pour qu’elles s’intègrent bien dans la disposition créée précédemment -->
@section Header {}
<!-- Créer une nouvelle vue « Statistiques » pour le contrôleur des tâches et faire en sorte qu’elle affiche les informations ci-dessus dans de simples libellés -->
<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NbTachesEnCours)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NbTachesEnCours)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NbTachesTerminees)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NbTachesTerminees)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NbTachesRetard)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NbTachesRetard)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MoyenneTpsTaches)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MoyenneTpsTaches)
        </dd>
    </dl>
</div>
<!-- Modifier les vues de tâches pour qu’elles s’intègrent bien dans la disposition créée précédemment -->
@section Footer {
    <footer>
        <p> &copy; 2020 - TodoList </p>
    </footer>
}

TodoList/Views/Taches/_Layout.cshtml
<!DOCTYPE html>
<!-- Page de disposition qui s’applique automatiquement à toutes les vues de gestion de tâches -->
<html>
<head>
    <!-- Reprendre les éléments <environnement> de la page de disposition par défaut, de façon à pouvoir utiliser la bibliothèque Bootstrap  -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body class="panel-body">
    <!-- Le style du titre est obtenu avec la classe de style page-header de Bootstrap -->
    <header class="page-header">
        @RenderSection("Header")
    </header>
    <!-- Toute la zone à droite du menu est contenue dans un panel possédant un titre, un corps et un pied. Utiliser pour cela les classes de style panel, panel-heading, panel-body et panel-footer de Bootstrap -->ontainer-fluid">
    <div class="row">
        <div class="col-md-2 navbav-dark bg-dark rounded">
            <ul class="nav flex-column">
                <li class="nav-item border-top">
                    <h1 class="text-light text-center" style="margin-top: 10px">TodoList</h1>
                </li>
                <li class="nav-item border-top">
                    <a class="nav-link active text-light text-center" style="margin-top: 10px" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light text-center" asp-controller="Taches" asp-action="Index">Tâches</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light text-center" asp-controller="Utilitaires" asp-action="Index">Utilitaires</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light text-center" asp-controller="Home" asp-action="About">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light text-center" asp-controller="Home" asp-action="ContactUs">Contact</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light text-center" asp-area="" asp-controller="Taches" asp-action="Statistiques">Statistiques</a>
                </li>
            </ul>
        </div>
        <div class="col-md-10">
            @RenderBody()
        </div>
    </div>
    <div class="panel-footer">@RenderSection("Footer")</div>
    </div>

    <!-- Reprendre les éléments <environnement> de la page de disposition par défaut, de façon à pouvoir utiliser la bibliothèque Bootstrap  -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

</body>
</html>